### ISSUE TITLE
Date not uploading correctly for different timezones

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-Swift#102]
When I update a custom date value to Parse, it does something wrong with the timezone. If I look in the database, it clearly shows that it added **_+1 hour_**. But when I read it in the app with ParseSwift, it shows it correctly. 

I think there is something wrong with the conversion of `Dates` when uploading and reading from Parse.

We also have a website, and with the Parse API for PHP it does upload the correct date. So if we look in the database, the `timeStamp` is the same as `updatedAt`. But when reading that same timeStamp value in ParseSwift, it makes the date **_-1 hour_**. This is causing some issues for us.

I have this code: 

```
let query = AppFiles.query("score" == score)
query.first(callbackQueue: .main) { results in
    switch results {
    case .success(var userFile):
        userFile.timeStamp = Date()
        
        userFile.save { result in
            switch result {
                case .success(_):
                    print("SUCCES")
                case .failure(let error):
                    print("FAIL")
                    print(error)
            }
        }
    case .failure(let error):
        print(error)
    }
}
```

This is a picture of what the dates look like when it is updated from the ParseSwift API:
<img width="481" alt="Schermafbeelding 2021-03-27 om 16 37 10" src="https://user-images.githubusercontent.com/44820440/112726022-7da84200-8f1b-11eb-8e2a-dc2784e14d25.png">

So to wrap this issue up: 

### When updating the timeStamp from ParseSwift:
**Dashboard shows this:** `2021-03-27 16:31:40 +0000`
**Logging in swift shows this:** `2021-03-27 15:31:40 +0000`

### When updating the timeStamp from Parse PHP:
**Dashboard shows this:** `2021-03-27 15:31:40 +0000`
**Logging in swift shows this:** `2021-03-27 14:31:40 +0000`

**Comment by cbaker6** [comment]
> When I update a custom date value to Parse, it does something wrong with the timezone. If I look in the database, it clearly shows that it added +1 hour. But when I read it in the app with ParseSwift, it shows it correctly.

The times stored on the server are in UTC (unless you change something on purpose), so you shouldn’t compare the time with what you expect unless you are doing a time zone conversion. It probably shows up correctly on your device because your app is converts the time back to it’s current time zone. When you use `userFile.timeStamp = Date()` in Swift this is using the local time zone set on the device which may not be UTC. In order to do an accurate comparison, you should make sure all date/times are in the same time zone. 

Be careful with entering/changing dates in the dashboard as it seems like there’s a bug in the Dashboard discussed here: https://community.parseplatform.org/t/error-decoding-parse-server-response/1446/21?u=cbaker6

**Comment by cbaker6** [comment]
Looks like this is a bug in the encoder/decoder. I will have the fix available shortly.

**Comment by novemTeam** [comment]
Oh thanks!

**Comment by cbaker6** [comment]
Let us know if the fix works out for you.

**Comment by novemTeam** [comment]
Issue is fixed! Thanks
