### ISSUE TITLE
Parse decoding error at ParseAuthentication linkCommand when sessionToken is missing from response

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/Parse-Swift#108]
I see a parse JsonDecoder error:

```
ParseError code=-1 error=Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x6000006e84c0> { URL: https://podlive-parse-server.herokuapp.com/parse/users/jXjF1qjJhw } { Status Code: 200, Headers {
    "Access-Control-Allow-Headers" =     (
        "X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control"
    );
    "Access-Control-Allow-Methods" =     (
        "GET,PUT,POST,DELETE,OPTIONS"
    );
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Access-Control-Expose-Headers" =     (
        "X-Parse-Job-Status-Id, X-Parse-Push-Status-Id"
    );
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        40
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Thu, 01 Apr 2021 13:24:07 GMT"
    );
    Etag =     (
        "W/\"28-69gFBc5Q54gsdpFK0tjSk36K+Xc\""
    );
    Server =     (
        Cowboy
    );
    Via =     (
        "1.1 vegur"
    );
    "X-Powered-By" =     (
        Express
    );
} }) with error: Die Daten konnten nicht gelesen werden, da sie fehlen. Format: Optional("{\"updatedAt\":\"2021-04-01T13:24:07.647Z\"}")
```

It says *data can not be read because its missing*.

I tracked it down to this location in ParseSwift code:

https://github.com/parse-community/Parse-Swift/blob/453ebdbcddf30cf3baad6bcf79fbc1fc0ba07fe2/Sources/ParseSwift/Authentication/Protocols/ParseAuthentication.swift#L429

The data object received from the server looks like this:

```
"{\"updatedAt\":\"2021-04-01T13:25:40.915Z\"}"
```

However ParseSwift expects this format:

```swift
internal struct UpdateSessionTokenResponse: Decodable {
    var updatedAt: Date
    let sessionToken: String
}
```

The sessionToken is missing.

This might be caused by using authentication wrong in my code. However I think a missing session token in the response should be handled explicitly by ParseSwift at this code location instead of just throwing an bad response format error.

What do you think?

**Comment by cbaker6** [comment]
Thanks for reporting!

Can you mention the steps you took when this occurred? For example, was the user originally logged in through password and then you linked to a specific auth type and the error threw? If so, what auth type? This was most likely a bug caused by the recent bug fixes to how an Anonymous user is handled in ParseSwift.

The fix "might" be as simple as changing the line you identified to optional to account for auth types that don't create a new sessionToken after being link (Anonymous auth creates a new session, the others don't). Can you submit a PR and I'll take a look? (depending on what auth type you tried to link)

```swift
internal struct UpdateSessionTokenResponse: Decodable {
    var updatedAt: Date
    let sessionToken: String?
}
```

**Comment by funkenstrahlen** [comment]
Thank you very much for your quick response. I am thankful to see you already opened a PR with a potential fix! ❤️ 

I currently only work with authentication via username and password together with anonymous users.

Could the missing `sessionToken` be caused by calling `ParseUser.anonymous.login` multiple times?

**Comment by cbaker6** [comment]
> Could the missing sessionToken be caused by calling ParseUser.anonymous.login multiple times?

Maybe, I would have to know more about your flow to answer this. If a user 1) Logs in anonymous (first session token) and then 2) Adds a username and password and logs in, a second/new session token will be sent from the server.

What would be the reason for calling anonymous.login multiple times? This could have caused the decoding error as the server probably doesn’t issue another sessionToken since you are already logged in. In this case, the PR will most likely still fix this error. This problem would have still crept up at some point though. For example, 1) Signup through password, 2) Link with Apple, Facebook, etc

**Comment by funkenstrahlen** [comment]
> What would be the reason for calling anonymous.login multiple times? This could have caused the decoding error as the server probably doesn’t issue another sessionToken since you are already logged in

There is actually no valid reason for calling anonymous.login multiple times. This was a bug in my code.

> In this case, the PR will most likely still fix this error. This problem would have still crept up at some point though. For example, 1) Signup through password, 2) Link with Apple, Facebook, etc

That's true. Feels good this is handled now.

Thank you for your help!
