### ISSUE TITLE
Update ParseFile with already known url

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#143]
I am able to save the ParseFile struct encoded as data in to a local realm database and then convert it back, but after I try to update the content i cannot get it saved:

    file.save { results in
          switch results {
          case .success(let savedFile):
              ....
          case .failure(let error):
              print("error saving file: \(file)")
              print(error)
          }

> error saving file: ParseFile(__type: "File", localId: 2478C4A2-3302-46D1-BB75-19A0E7B09641, name: "2adcf21bf5a9bb8223ba693fd58963dc_0.jpg", url: Optional(https://parsefiles.back4app.com/coYfuTYV3z35Z8iwv8q3NOTdGQs2ywJtt7tUUg4p/2adcf21bf5a9bb8223ba693fd58963dc_0.jpg), localURL: nil, cloudURL: nil, data: Optional(71997 bytes), mimeType: nil, metadata: nil, tags: nil, options: Set([]))

> ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x7feec2f04d00> { URL: https://parseapi.back4app.com/files/2adcf21bf5a9bb8223ba693fd58963dc_0.jpg } { Status Code: 404, Headers {... }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"message\\\":\\\"Not Found\\\",\\\"error\\\":{}}\")")

as you can see the url in request is not the url that I have already in the file. Is it correct that the the following SDK code is generating the url again?

    private static func updateFileCommand(_ object: ParseFile) -> API.Command<ParseFile, ParseFile> {
            API.Command(method: .PUT,
                        path: .file(fileName: object.name),
                        uploadData: object.data,
                        uploadFile: object.localURL) { (data) -> ParseFile in
                try ParseCoding.jsonDecoder().decode(FileUploadResponse.self, from: data).apply(to: object)
            }
        }

the **path: .file(fileName: object.name),** seems to get it wrong.. shouldn't there be **path: object.url** ?

**Comment by cbaker6** [comment]
> the path: .file(fileName: object.name), seems to get it wrong.. shouldn't there be path: .file(fileName: object.name) ?

I don’t see the difference between what you are proposing and what’s already there

**Comment by lsmilek1** [comment]
Copy paste error, sorry. I would expect that there is the existing url being passed to the request. I am not sure how does the unique id and url works during the save though.

**Comment by cbaker6** [comment]
I believe your proposed solution was moving in the right direction. Unfortunately, I don't believe the server supports updating a file from what I can see in the [server tests](https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/spec/ParseFile.spec.js) (no `PUT`) and also from what's shown in the [REST documentation](https://docs.parseplatform.org/rest/guide/#files). I will remove the uploadFileCommand from the Swift SDK.

In your case, you will want the update to create a new ParseFile with a new URL. Then you will probably want to implement some piece of cloud code that deletes the old file for you since you can't delete files from the client without the masterKey. You can write some cloud code that periodically goes through your database and removes files that are no longer attached to a ParseObject after a period of time.

**Comment by lsmilek1** [comment]
Aaaah, now I get it. I somehow understood it is possible to rewrite the data of the given ParseFile. I will have look deeper on why this is not supported. For now I will follow the [example in documentation](https://docs.parseplatform.org/cloudcode/guide/#aftersavefile) to keep track of the files in separate class where the afterSave on the object would check and eventually delete not used files. Thank you for your prompt response!

**Comment by cbaker6** [comment]
Thanks for reporting as this uncovered I shouldn't have added `updateFileCommand` to the Swift SDK.

My guess is because the parse file url is known to be public, you don't want to allow anyone to update the file. So files can only be created and deleted through the files endpoint.
