### ISSUE TITLE
Tree Parse object

### ISSUE THREAD

**Issue by boardmain** [parse-community/Parse-Swift#161]
Hi i have a Tree object

with parent is object of the same type

how can i solve this?

```
struct Pagina : ParseObject {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var titolo: [String: String]?
    var parent: Pagina? <--- i can't do this because we are in a struct...
}
```

**Comment by cbaker6** [comment]
You cannot do this with a struct as the compiler will not allow it, plus you can easily create a cycle.

A class can do this, but this SDK isn’t designed for classes, so you will most likely run into threading issues. Still shouldn’t do this because of the cycle I mentioned earlier.

A workaround would be change the parent property to parentObjectId: String? and store the objectId of the parent. Whenever you need the parent, fetch it based off the objectId

**Comment by boardmain** [comment]
> You cannot do this with a struct as the compiler will not allow it, plus you can easily create a cycle.
> 
> A class can do this, but this SDK isn’t designed for classes, so you will most likely run into threading issues. Still shouldn’t do this because of the cycle I mentioned earlier.
> 
> A workaround would be change the parent property to parentObjectId: String? and store the objectId of the parent. Whenever you need the parent, fetch it based off the objectId

yes i think for now can i only do that  :/ 

thank you
