### ISSUE TITLE
How to register for push notification?

### ISSUE THREAD

**Issue by boardmain** [parse-community/Parse-Swift#171]
Hi, how to register for the parse push notification?

i don't find it in the documentation

**Comment by TomWFox** [comment]
See [ParseInstallation in the API reference](http://parseplatform.org/Parse-Swift/api/Protocols/ParseInstallation.html).

You may also want to take a look at the [PR which introduced push support](https://github.com/parse-community/Parse-Swift/pull/78).

**Comment by cbaker6** [comment]
Following the documentation and PR @TomWFox  sent, you can add the following code to your AppDelegate class:

```swift
func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        guard var currentInstallation = Installation.current else {
            return
        }
        currentInstallation.setDeviceToken(deviceToken)
        currentInstallation.channels = ["global"] // Look at further documentation to set your channels
        currentInstallation.save { _ in }
    }
}
```

Be sure to register for notifications using [Apple's process](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns). You can learn more about the Installation properties for notifications in the [documentation](https://docs.parseplatform.org/rest/guide/#push-notifications).

**Comment by boardmain** [comment]
> ```swift
>  L
> ```

Thank you found it in the playground

**Comment by lsmilek1** [comment]
Do we need to save `Installation.current` first in the device? I found in other issue that the `ParseInstallation` is created and saved automatically in ParseSwift init. but in my case it is still `Installation.current == nil` even after user login

**Comment by cbaker6** [comment]
Yes, installation needs to be saved for notifications.

>  I found in other issue that the ParseInstallation is created and saved automatically in ParseSwift init. but in my case it is still Installation.current == nil even after user login

this shouldn’t be possible with the later version of the SDK. The testcases make sure that this isn’t isn’t broken. Are you doing something custom with Installations?

**Comment by lsmilek1** [comment]
Nothing I would be aware of... Struct is copy pasted from playgrouns: 

```swift
import Foundation
import ParseSwift

struct Installation: ParseInstallation {
    //: These are required for `ParseObject`.
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    //: These are required for `ParseInstallation`.
    var installationId: String?
    var deviceType: String?
    var deviceToken: String?
    var badge: Int?
    var timeZone: String?
    var channels: [String]?
    var appName: String?
    var appIdentifier: String?
    var appVersion: String?
    var parseVersion: String?
    var localeIdentifier: String?

}
```

and these are the first lines in AppDelegate I am using when learning about push notifications:
```swift
   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ParseSwift.initialize(applicationId: "...",
                              clientKey: "...",
                              serverURL: URL(string: "https://parseapi.back4app.com")!,
                              liveQueryServerURL: URL(string: "https://felse.b4a.io")!,
                              allowCustomObjectId: true)
        print(Realm.Configuration.defaultConfiguration.fileURL as Any) //line to find realm file location
        initializeRealm()
        getNotificationSettings()        
        return true
    }

   func getNotificationSettings() {
        UNUserNotificationCenter.current().getNotificationSettings { settings in
            print("Notification settings: \(settings)")
            guard settings.authorizationStatus == .authorized || settings.authorizationStatus == .provisional else { return }
            DispatchQueue.main.async {
                UIApplication.shared.registerForRemoteNotifications()
            }
        }
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let parseService: ParseService?
        if let tabMainVC = UIApplication.topViewController() as? TabMainViewController {
            parseService = tabMainVC.parseService
        } else if let injectedTableVC = UIApplication.topViewController() as? InjectedTableViewController {
            parseService = injectedTableVC.parseService
        } else if let injectedVC = UIApplication.topViewController() as? InjectedViewController {
            parseService = injectedVC.parseService
        } else {
            parseService = nil
            print("Cannot save ParseInstallation as parse service is nil.")
        }
        print("TopVC: \(String(describing: UIApplication.topViewController()))")
        parseService?.createInstallationOnParse(deviceTokenData: deviceToken)
    }
```

Unfortunatelly I am hitting nil when trying to save Installation:
```swift
extension ParseService {
    
    func createInstallationOnParse(deviceTokenData: Data) {
        print("ParseService.createInstallation(), current installation: \(String(describing: Installation.current))")
        Installation.current?.setDeviceToken(deviceTokenData)
        Installation.current?.save(isIgnoreCustomObjectIdConfig: true, completion: { result in
            switch result {
            case .success(let savedInstallation): print("saved installation: \(savedInstallation)")
            case .failure(let error):
                print("error saving installation: \(error)")
                print("TODO: mark installation for retry save")
            }
        })
    }    
}
```

I have not used `ParseInstallation` before. I need to double check, if I am not deleting it from keychain somehow through `User.logout` by accident...

**Comment by cbaker6** [comment]
I’m not able to replicate the installation being nil. There are a number of tests to make sure this is automatically created by the SDK and that changes don’t break the process. You should check to make sure you are not overriding it with nil with your customObjectId setup. There is no parse server needed to run any test.

I recommend running the test cases and setting break points. If your local SDK is passing the tests, then the issue is problem something on your end.

https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Tests/ParseSwiftTests/InitializeSDKTests.swift#L72-L238

After login test, a number of other tests in this file: https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Tests/ParseSwiftTests/ParseInstallationTests.swift#L130-L146

https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Tests/ParseSwiftTests/ParseUserTests.swift#L1101-L1145

You can also connect to playgrounds to your own server and test the there.

**Comment by cbaker6** [comment]
For this line: 
```swift
func createInstallationOnParse(deviceTokenData: Data) {
        print("ParseService.createInstallation(), current installation: \(String(describing: Installation.current))")
```

Can you check for nil instead of trying to print the stunt? The debugger doesn’t always show optional values properly until unwrapped.

**Comment by lsmilek1** [comment]
Checking against nil is giving the same result. For both device and simulator the same. What I noticed is that if I erase the simulator completely (with keychain) it returns installation on the first app launch:
```swift
   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ParseSwift.initialize(applicationId: "coYfuTYV3z35Z8iwv8q3NOTdGQs2ywJtt7tUUg4p",
                              clientKey: "L8PDqQEMofo44rf9XJTegf5uWGJTDhIdU0wQ87gl",
                              serverURL: URL(string: "https://parseapi.back4app.com")!,
                              liveQueryServerURL: URL(string: "https://felse.b4a.io")!,
                              allowCustomObjectId: true)
        print(Realm.Configuration.defaultConfiguration.fileURL as Any) //line to find realm file location
        initializeRealm()
        print("installation is nil: \(Installation.current == nil)")
        getNotificationSettings()        
        return true
    }
```
> installation is nil: false

That is when it goes through line 142, creating the new one. Not touching anything in the app, not even calling `User.logout()` and just restarting the app it again gives further only nil

> installation is nil: true

So it seems that it is created, but then it is getting somewhere lost. As you mentioned, the line 144 is giving it back, so it should not be nil. I checked and the KeychainStore is returning the same 57 bytes (on line 159) that it stored during the first run when asked for "_currentInstallation" (line 475) on the second and further app launch:

https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Sources/ParseSwift/Storage/KeychainStore.swift#L144-L160

This in next step returns an object on line 87:
https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Sources/ParseSwift/Storage/KeychainStore.swift#L79-L91
that I cant print through breakpoint with error pointing at `CurrentInstallationContainer<Felse.Installation>`:
> Printing description of object:
expression produced error: error: /var/folders/h6/q1hzw4q15nb81pfm64vvs7180000gn/T/expr90-2dea49..swift:1:76: error: 'CurrentInstallationContainer' is not a member type of struct 'ParseSwift.ParseSwift'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<ParseSwift.CurrentInstallationContainer<Felse.Installation>>(bitPattern: 0x111c754b0)!.pointee)
                                                                ~~~~~~~~~~ ^
ParseSwift.ParseSwift:1:15: note: 'ParseSwift' declared here
public struct ParseSwift {

but it is still returning an object from the Keychain. I tried to name the struct `InstallationX` to check if there would be some other class or module with same name, but it behaves the same. When I added some print statements:
```swift
func object<T>(forKey key: String) -> T? where T: Decodable {
        guard let data = synchronizationQueue.sync(execute: { () -> Data? in
            return self.data(forKey: key)
        }) else {
            return nil
        }
        do {
            let object = try ParseCoding.jsonDecoder().decode(T.self, from: data)
            print("decoded object from keychain key: \(key): \(object)")
            return object
        } catch {
            print("returning nil for keychain key: \(key)")
            return nil
        }
    }
```
I got: 
> decoded object from keychain key: _currentInstallation: CurrentInstallationContainer<Installation>(currentInstallation: nil, installationId: Optional("9f0cbc15-24ea-4831-919e-7b2aa00ebd28"))

so the container is not nil, but the installation itself is not there. I found the following is happening during the first app launch: 

1) line 143 returns empty container
> return newInstallation: CurrentInstallationContainer<BaseParseInstallation>(currentInstallation: nil, installationId: Optional("b3ccf20d-dddd-42c1-9e3f-485c5ec7ef2b"))
2) the empty container goes to 202-203:
https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Sources/ParseSwift/Objects/ParseInstallation.swift#L193-L202
3) from there is the struct in `Self.currentInstallationContainer.currentInstallation` updated properly as the installation in `didFinishLaunchingWithOptions` has all properties on the first launch (as it is being hold as variable in memory..?)
>installation: Optional(_Installation ({"timeZone":"Europe\/Berlin","appVersion":"2","appName":"Felse","installationId":"f4ec6107-8d0b-4718-801b-33e97c64c3ea","deviceType":"ios","appIdentifier":"app.felse","parseVersion":"1.9.9","localeIdentifier":"en-US"}))

4) but I think there is missing save into the Keychain after that. At least through breakpoints I have not noticed it would save the updated values into the Keychain.

Could it be perhaps related to this commit?
https://github.com/parse-community/Parse-Swift/commit/85b3e764c11580fcd0f0658cf760dc0d461f1d90

I believe the tests are not failing because they use the struck updated and still kept in memory (`Self.currentInstallationContainer.currentInstallation`)?

**Comment by cbaker6** [comment]
Can you open a new issue? You can you link back to the discussion here when completing the form for the issue.
