### ISSUE TITLE
Add async/await for Swift 5.5

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#234]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation

Swift 5.5 offers new async/await ability that current isn't in the SDK

### Feature / Enhancement Description

Allows async methods to be treated like sync methods allowing for better readability when coding.

### Alternatives / Workarounds

User current sync and async completion methods

**Comment by lsmilek1** [comment]
As I moved to Xcode 13 I am looking into this async/await if it can help to de-spaghettise my code and I would have two questions:
1) In `ParseObject+async` I have not noticed a `.find()` wrapper, is this intentional?
2) It seems that the wrappers are not passing `isIgnoreCustomObjectIdConfig`. I believe this is due to timeline and there is no conflict in implementing this?

Thank you for quick clarification!

**Comment by cbaker6** [comment]
This PR is in “draft” state and still being worked on. Everything will be added by the time it moves out of draft state

**Comment by cbaker6** [comment]
> In ParseObject+async I have not noticed a .find() wrapper, is this intentional?

Find has already been added to query: https://github.com/parse-community/Parse-Swift/blob/e63d242059ee5a0846d8d54dc70860c1fe39c5c2/Sources/ParseSwift/Types/Query%2Basync.swift#L22-L27

Are you referring to something else?
