### ISSUE TITLE
containedIn does not work with LiveQuery

### ISSUE THREAD

**Issue by EliteTechnicalCare** [parse-community/Parse-Swift#296]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
containedIn query does not update LiveQuery

### Steps to reproduce
Subscribe to a LiveQuery with a containedIn, will not update such as:
`query = query.where(containedIn(key: "parties", array: [usersProfile.id]))`

But a normal equals query seems to update perfectly:
`query = query.where("senderID" == "VcF9fMCyKb")`

### Actual Outcome
Nothing, it will not update at all. Note the query containedIn loads perfectly fine when using fetch or even using the subscribedQuery but will not activate any of the events.

### Environment

Client
- Parse Swift SDK version: 2.3.1
- Xcode version: 13.1
- Operating system (iOS, macOS, watchOS, etc.): macOS
- Operating system version: 12.0.1

Server
- Parse Server version: 4.4.0
- Operating system: No idea
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Back4App

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 3.6
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Back4App

### Logs
When using containedIn
`Successfully subscribed to new query Message ({"limit":100,"skip":0,"_method":"GET","where":{"parties":{"$in":["CwyLdNXNAH"]}}})
Saved Message`

When using equals to (as you can see it updates both new messages and editing old ones)

```
Successfully subscribed to new query Message ({"limit":100,"skip":0,"_method":"GET","where":{"senderID":"VcF9fMCyKb"}})
Saved Message
Optional([Message ({"spouseID":"CwyLdNXNAH","time":{"__type":"Date","iso":"2021-12-07T23:09:16.057Z"},"senderID":"VcF9fMCyKb","read":true,"text":"Nice","objectId":"O0rkPsUIVw","updatedAt":{"__type":"Date","iso":"2021-12-07T23:26:08.452Z"},"createdAt":{"__type":"Date","iso":"2021-12-07T23:09:16.127Z"},"parties":["VcF9fMCyKb","CwyLdNXNAH"]}), Message ({"spouseID":"CwyLdNXNAH","time":{"__type":"Date","iso":"2021-12-08T00:15:56.536Z"},"senderID":"VcF9fMCyKb","read":true,"text":"Ok wow","objectId":"KBz1yl6SHs","updatedAt":{"__type":"Date","iso":"2021-12-08T00:34:56.260Z"},"createdAt":{"__type":"Date","iso":"2021-12-08T00:15:56.639Z"},"parties":["VcF9fMCyKb","CwyLdNXNAH"]})])
Updated: Message ({"spouseID":"CwyLdNXNAH","time":{"__type":"Date","iso":"2021-12-08T00:15:56.536Z"},"senderID":"VcF9fMCyKb","read":true,"text":"Ok wow","objectId":"KBz1yl6SHs","updatedAt":{"__type":"Date","iso":"2021-12-08T00:34:56.260Z"},"createdAt":{"__type":"Date","iso":"2021-12-08T00:15:56.639Z"},"parties":["VcF9fMCyKb","CwyLdNXNAH"]})
Updated: Message ({"spouseID":"CwyLdNXNAH","time":{"__type":"Date","iso":"2021-12-07T23:09:16.057Z"},"senderID":"VcF9fMCyKb","read":true,"text":"Nice too","objectId":"O0rkPsUIVw","updatedAt":{"__type":"Date","iso":"2021-12-08T00:35:07.796Z"},"createdAt":{"__type":"Date","iso":"2021-12-07T23:09:16.127Z"},"parties":["VcF9fMCyKb","CwyLdNXNAH"]})
Entered: Message ({"spouseID":"VcF9fMCyKb","time":{"__type":"Date","iso":"2021-12-07T23:26:20.541Z"},"senderID":"VcF9fMCyKb","read":true,"text":"Cool","objectId":"gJCz7b6cIW","updatedAt":{"__type":"Date","iso":"2021-12-08T00:36:17.128Z"},"createdAt":{"__type":"Date","iso":"2021-12-07T23:26:20.635Z"},"parties":["CwyLdNXNAH","VcF9fMCyKb"]})
```

**Comment by cbaker6** [comment]
LiveQuery doesn't support every type of query. You can see one of the new PR's on the server that added more constraints, https://github.com/parse-community/parse-server/pull/7113. If you find something missing that you think should be added on the server, I suggest opening an issue there with a possible PR to fix.

If you find `containedIn` not working in a regular query, your issue should be created in this repo.

**Comment by lsmilek1** [comment]
Pardon additional question... Is this issue about updating the query after it is subscribed for the first time? Because I am actually using "containedIn" as per command above and it is working. I just have to unsubscribe it and subscribe again whenever I need to change the array of the criteria

**Comment by EliteTechnicalCare** [comment]
> Pardon additional question... Is this issue about updating the query after it is subscribed for the first time? Because I am actually using "containedIn" as per command above and it is working. I just have to unsubscribe it and subscribe again whenever I need to change the array of the criteria

No unfortunately despite the subscription I would get zero updates/deletions etc. What version of parse server are you on?

**Comment by cbaker6** [comment]
@EliteTechnicalCare you should provide more information in your question. For example, show all of your complete `ParseObject`'s in question.

I suspect the `parties` field is actually of type "pointer", if so, your query isn't correct.

Also, you should check if your regular `containedIn` query works before trying it with LiveQuery. The examples you showed are completely different from each other and aren't checking the same property:

> query = query.where(containedIn(key: "parties", array: [usersProfile.id]))
> query = query.where("senderID" == "VcF9fMCyKb")

For questions, you should ask here: https://community.parseplatform.org

as oppose to opening issues.

**Comment by EliteTechnicalCare** [comment]
> @EliteTechnicalCare you should provide more information in your question. For example, show all of your complete `ParseObject`'s in question.
> 
> I suspect the `parties` field is actually of type "pointer", if so, your query isn't correct.
parties is an Array not a pointer.


> Also, you should check if your regular `containedIn` query works before trying it with LiveQuery. The examples you showed are completely different from each other and aren't checking the same property:
> 
> > query = query.where(containedIn(key: "parties", array: [usersProfile.id]))
> > query = query.where("senderID" == "VcF9fMCyKb")
As I specified in my original post, the query works perfectly fine, it simply doesn't auto update after the initial fetch.


> For questions, you should ask here: https://community.parseplatform.org
> 
> as oppose to opening issues.
What question have I asked this entire thread?

**Comment by cbaker6** [comment]
Your original post and everything after doesn’t signal there’s an actual issue. You haven’t provided enough information to elude to an issue or even replicate an issue. It seems, from your post, you are probably not setting up your queries correctly which is why this is labeled as a question. If your ask the question, “how to properly setup a live query using containedIn?” on the link I provided and provide the details of your ParseObjects and queries, you will most likely get what you need. If there happens to be a bug with correct setup, then you should open an issue.

**Comment by EliteTechnicalCare** [comment]
> you are probably not setting up your queries correctly 

Which is why it works perfectly fine until I attempt a LiveQuery with it. I haven't asked a question, I understand how queries work. They are working perfectly fine, the only issue is when I use a query with containedIn with LiveQuery.  Every other query ive tested works fine with LiveQuery. So I know how to use LiveQuery. Every time Ive used containedIn for normal queries works fine. So I know how to use containedIn. Only issue I am having is when I am using containedIn with LiveQuery. 

@lsmilek1 says it works with him so the only thing I asked him was what server version he is running. I am not denying that this could very well be a server issue, but I am not here for a tutorial on how to do queries. Rather, I am trying to pin point where the issue is and report it (if need be).

I am not trying to be difficult, I have left this issue closed etc but would be good to see what server version he is running so I can move forward in the right direction.

**Comment by cbaker6** [comment]
> Every time Ive used containedIn for normal queries works fine. So I know how to use containedIn. Only issue I am having is when I am using containedIn with LiveQuery.

I stated [here](https://github.com/parse-community/Parse-Swift/issues/296#issuecomment-990590085), you provided examples that are "completely different" from each other, essentially you provided an apples to oranges comparison. 

Proper steps to flush out where your problem is:

1. create a simple `==` query, `find` the results, are they correct?
2. use the query in "1" as a live query, do you receive the proper updates?
3. create a simple `containedIn` query, `find` the results, are they correct? (you have not provided anything that shows you have done this the entire thread, thus making it extremely hard to help you)
4. use the query in "3" as a live query, do you receive the proper updates?

If 1,2, and 3 works and 4 doesn't, then either: 

1. LiveQuery doesn't support `containedIn, or 
2. LiveQuery doesn't support `containedIn` in the version of the server you are using

In any of the cases, you should be providing enough information when asking a question or opening an issue. Enough information requires providing your `ParseObject`'s to understand your setup.  In addition, you should take the debugging steps necessary to isolate your problem (1-4 above) and show the results of these steps.

**Comment by cbaker6** [comment]
> parties is an Array not a pointer.

`parties` is an array of what exactly? Your query attempts to treat it as an "array of strings", particularly containing `objectId`'s. I ask if this is an array of "pointers" to `ParseObject`'s because if it is, your query is incorrect.

> As I specified in my original post, the query works perfectly fine, it simply doesn't auto update after the initial fetch.

We will need you to provide necessary information I asked for in the previous comments to determine if it's indeed "perfectly fine."
